name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server:  ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          sudo yum -y install docker
          docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}.azurecr.io:${{ github.sha }}
